const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Module = require('node:module');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-presets-'));
const originalLoad = Module._load;
const handlers = new Map();
Module._load = function(name, ...args) {
  if (name === 'electron') return { app: { isReady: () => true, getPath: () => root }, ipcMain: { handle: (name, fn) => handlers.set(name, fn), removeHandler: name => handlers.delete(name) } };
  return originalLoad.call(this, name, ...args);
};
const { db, initDatabase, closeDatabase } = require('../src/main/db');
const agents = require('../src/main/agentManager');
const sessions = require('../src/main/sessionManager');
const { prepareChatMessages } = require('../src/main/promptBuilder');
const { registerIpcHandlers } = require('../src/main/ipcHandlers');
(async () => {
  let dispose;
  try {
    initDatabase();
    const builtins = agents.listAgents();
    assert.equal(builtins.length, 3);
    assert.equal(builtins.find(agent => agent.name === 'Creative Writer').sampling_params.temperature, 0.9);
    closeDatabase(); initDatabase();
    assert.equal(agents.listAgents().length, 3);
    const preset = agents.createAgent({ name: 'Test Agent', description: 'Testing', system_prompt: 'Respond with exactly two bullets.', avatar_url: 'data:image/jpeg;base64,/9j/', model_id: 'model-a', sampling_params: { temperature: 0.25 } });
    const copied = agents.duplicateAgent(preset.id);
    assert.notEqual(copied.id, preset.id); assert.equal(copied.system_prompt, preset.system_prompt);
    const applied = agents.applyAgent('draft', preset.id, 'fallback');
    assert.equal(applied.modelId, 'model-a');
    assert.equal(sessions.getSessionSamplingParams('draft').params.temperature, 0.25);
    assert.equal(agents.getSessionAgent('draft').avatar_url, preset.avatar_url);
    agents.updateAgent(preset.id, { ...preset, system_prompt: 'Changed prompt' });
    assert.equal(agents.getSessionAgent('draft').system_prompt, 'Respond with exactly two bullets.');
    const prompt = prepareChatMessages({ sessionId: 'draft', modelId: 'model-a', userText: 'Hello' });
    assert.match(prompt[0].content, /Respond with exactly two bullets/);
    assert.match(prompt[0].content, /MEMORY & CONVERSATION RULES/);
    const message = sessions.loadSession('draft').messages[0];
    const branch = sessions.branchChat('draft', message.id);
    assert.deepEqual(agents.getSessionAgent(branch.sessionId), agents.getSessionAgent('draft'));
    const originalTuning = sessions.getSessionSamplingParams('draft').params;
    agents.saveSessionPrompt('draft', 'Session-only instructions.', 'model-a');
    assert.equal(agents.getSessionAgent('draft').system_prompt, 'Session-only instructions.');
    assert.equal(agents.getAgent(preset.id).system_prompt, 'Changed prompt');
    assert.deepEqual(sessions.getSessionSamplingParams('draft').params, originalTuning);
    agents.saveSessionPrompt('custom', 'Custom session prompt.', 'model-a');
    assert.equal(agents.getSessionAgent('custom').id, null);
    assert.match(prepareChatMessages({ sessionId: 'custom', modelId: 'model-a', userText: 'hello' })[0].content, /Custom session prompt/);
    agents.saveSessionPrompt('custom', '', 'model-a');
    assert.equal(agents.getSessionAgent('custom').system_prompt, '');
    agents.deleteAgent(preset.id);
    assert.equal(agents.getSessionAgent('draft').name, 'Test Agent');
    agents.applyAgent('draft', null, 'model-a');
    assert.equal(agents.getSessionAgent('draft'), null);
    assert.equal(sessions.getSessionSamplingParams('draft').params.temperature, 0.7);
    const noModel = agents.createAgent({ name: 'No default', system_prompt: 'Hello' });
    agents.applyAgent('empty', noModel.id, '');
    assert.equal(sessions.loadSession('empty').model_id, null);
    assert.throws(() => agents.createAgent({ name: '', system_prompt: 'test' }), /name/);
    assert.throws(() => agents.createAgent({ name: 'Bad', system_prompt: 'test', sampling_params: { temperature: 99 } }), /sampling/);
    db.prepare("UPDATE sessions SET is_compressing = 1 WHERE id = 'draft'").run();
    assert.throws(() => agents.applyAgent('draft', noModel.id, 'model'), /summarized/);
    agents.deleteAgent(builtins[0].id);
    const beforeRestart = agents.listAgents().length;
    closeDatabase(); initDatabase();
    assert.equal(agents.listAgents().length, beforeRestart);
    assert.throws(() => agents.getAgent(builtins[0].id), /not found/);
    dispose = registerIpcHandlers({ isTrustedSender: event => event.trusted });
    await assert.rejects(handlers.get('agents:create')({ trusted: false }, { name: 'Bad' }), /Unauthorized/);
    const result = await handlers.get('agents:create')({ trusted: true }, { name: 'IPC agent', system_prompt: 'Be kind.' });
    await handlers.get('agents:apply')({ trusted: true }, { sessionId: 'ipc-chat', agentId: result.id, modelId: 'model' });
    assert.equal((await handlers.get('agents:session')({ trusted: true }, { sessionId: 'ipc-chat' })).name, 'IPC agent');
    console.log('Agent seeding, CRUD, duplication, validation, persistence, prompt injection, sampling/avatar snapshots, branches, and IPC passed.');
  } finally { dispose?.(); closeDatabase(); Module._load = originalLoad; fs.rmSync(root, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
