// Run: env -u ELECTRON_RUN_AS_NODE xvfb-run -a node_modules/electron/dist/electron --no-sandbox tests/chatHistory.ui.cjs
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const esbuild = require('esbuild');
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'chat-history-ui-'));
  const window = new BrowserWindow({ width: 700, height: 740, show: false, webPreferences: { sandbox: true } });
  try {
    await esbuild.build({ entryPoints: [path.join(__dirname, 'fixtures/chatHistory.jsx')], bundle: true, outfile: path.join(directory, 'fixture.js'), define: { 'process.env.NODE_ENV': '"test"' } });
    const assets = path.join(__dirname, '../dist/assets');
    const css = (await fs.readdir(assets)).find(name => name.endsWith('.css'));
    await fs.writeFile(path.join(directory, 'index.html'), `<html><head><link rel="stylesheet" href="${pathToFileURL(path.join(assets, css)).href}"></head><body><div id="root"></div><script src="fixture.js"></script></body></html>`);
    await window.loadFile(path.join(directory, 'index.html'));
    const result = await window.webContents.executeJavaScript(`(async () => {
      const tick = () => new Promise(resolve => setTimeout(resolve, 40));
      const check = (value, message) => { if (!value) throw new Error(message); };
      const button = (root, text) => [...root.querySelectorAll('button')].find(b => b.textContent.trim() === text);
      const row = id => document.querySelector('[data-session-id="' + id + '"]');
      for (let i = 0; i < 100 && !row('a'); i++) await tick();
      check(document.querySelector('nav section').getAttribute('aria-label') === 'Empty folder', 'Folders first including empty folders');
      check(row('a').textContent.includes('12K tokens'), 'Compact token count');
      const before = row('b').getBoundingClientRect().top;
      const actions = row('a').querySelector('[aria-haspopup]');
      actions.click(); await tick();
      const menu = document.querySelector('[role=menu]');
      check(getComputedStyle(menu).position === 'absolute', 'Menu absolute positioning');
      check(getComputedStyle(menu).zIndex === '50', 'Menu z-50');
      check(menu.parentNode === document.body, 'Menu outside clipping sidebar');
      check(row('b').getBoundingClientRect().top === before, 'Opening menu must not move rows');
      menu.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await tick();
      check(!document.querySelector('[role=menu]') && document.activeElement === actions, 'Escape restores focus');
      actions.click(); await tick();
      button(document.querySelector('[role=menu]'), 'Move to Folder').click(); await tick();
      const dialog = document.querySelector('dialog');
      check(dialog.open, 'Native modal opens');
      check(dialog.querySelectorAll('input[type=radio]').length === 3, 'All folders and unassigned destination');
      dialog.querySelector('input[value="Empty folder"]').click();
      button(dialog, 'Move chat').click(); await tick();
      check(window.lastAction.id === 'a' && window.lastAction.value === 'Empty folder', 'Move targets correct chat');
      check(row('a').closest('section').getAttribute('aria-label') === 'Empty folder', 'Moved chat rendered in destination');
      const search = document.querySelector('input[type=search]');
      const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set;
      setter.call(search, 'Weekend'); search.dispatchEvent(new Event('input', { bubbles: true })); await tick();
      check(!row('a') && row('b'), 'Search filters chats');
      setter.call(search, ''); search.dispatchEvent(new Event('input', { bubbles: true })); await tick();
      document.querySelector('[aria-label="New Folder"]').click(); await tick();
      const name = document.querySelector('[aria-label="Folder name"]');
      setter.call(name, 'Research'); name.dispatchEvent(new Event('input', { bubbles: true })); await tick();
      button(document.querySelector('dialog'), 'Create folder').click(); await tick();
      const folder = document.querySelector('section[aria-label="Research"]');
      check(folder && folder.textContent.includes('Drop chats here'), 'New empty folder rendered');
      const transfer = new DataTransfer(); transfer.setData('application/x-chat-session', 'b');
      folder.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: transfer }));
      folder.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: transfer })); await tick();
      check(window.lastAction.id === 'b' && window.lastAction.value === 'Research', 'Drag moves correct chat');
      check(row('b').closest('section') === folder, 'Drag assignment rendered');
      folder.querySelector('button').click(); await tick();
      check(folder.querySelector('button').getAttribute('aria-expanded') === 'false' && !row('b'), 'Folder collapses');
      return true;
    })()`);
    assert.equal(result, true);
    console.log('Floating menus, keyboard focus, token counts, search, folder picker, creation, drag-and-drop, and collapse passed.');
  } finally { window.destroy(); await fs.rm(directory, { recursive: true }); }
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
