const { app, BrowserWindow } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const esbuild = require('esbuild');
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'cloud-ui-'));
  const window = new BrowserWindow({ show: false, webPreferences: { sandbox: true } });
  try {
    await esbuild.build({ entryPoints: [path.join(__dirname, 'fixtures/cloudSelection.jsx')], bundle: true, outfile: path.join(directory, 'fixture.js'), define: { 'process.env.NODE_ENV': '"test"' } });
    await fs.writeFile(path.join(directory, 'index.html'), '<div id="root"></div><script src="fixture.js"></script>');
    await window.loadFile(path.join(directory, 'index.html'));
    await window.webContents.executeJavaScript(`(async () => {
      const tick = () => new Promise(resolve => setTimeout(resolve, 40));
      const check = (value, message) => { if (!value) throw new Error(message); };
      const button = text => [...document.querySelectorAll('dialog[open] button')].find(button => button.textContent.includes(text));
      for (let i = 0; i < 100 && !button('OpenAI'); i++) await tick();
      check(document.querySelector('dialog').textContent.includes('Local Engine Status'), 'Engine banner');
      check(!button('OpenAI').disabled, 'Cloud enabled with local loaded');
      check(!button('Anthropic'), 'Unconfigured providers are hidden');
      button('OpenAI').click(); await tick();
      check(!document.querySelector('dialog[open]'), 'Cloud selection closes dialog');
      check(window.fixtureState.target.type === 'cloud', 'Cloud selected');
      check(window.fixtureState.loaded.id === '/first.gguf', 'Local stays in VRAM');
      check(!window.calls.loads.length && !window.calls.kills, 'No engine operations for cloud');
      document.querySelector('#open').click(); await tick();
      button('First local').click(); await tick();
      check(window.fixtureState.target.type === 'local', 'Reuse loaded local');
      check(!window.calls.loads.length, 'No redundant reload');
      document.querySelector('#open').click(); await tick();
      button('Second local').click(); await tick();
      check(document.querySelector('#load-settings-title'), 'Different local opens load sequence');
      button('Load model').click(); await tick();
      check(window.calls.loads[0] === '/second.gguf', 'New local is loaded');
      document.querySelector('#open').click(); await tick();
      button('OpenAI').click(); await tick();
      document.querySelector('#open').click(); await tick();
      button('Unload').click(); await tick();
      check(!window.fixtureState.loaded && window.fixtureState.target.type === 'cloud', 'Unload keeps cloud active');
      document.querySelector('[aria-label="Close model selector"]').click(); await tick();
      const form = [...document.querySelectorAll('form')].find(form => form.textContent.includes('OpenAI'));
      const key = form.querySelector('input[type=password]');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(key, 'new-key');
      key.dispatchEvent(new Event('input', { bubbles: true })); await tick();
      form.requestSubmit(); await tick();
      check(window.calls.saves[0].apiKey === 'new-key', 'Key reaches persistent settings bridge');
      check(key.value === '', 'Key cleared from form after save');
      [...document.querySelectorAll('button')].find(button => button.textContent === '+ Add Custom Provider').click(); await tick();
      const custom = [...document.querySelectorAll('form')].at(-1);
      const inputs = custom.querySelectorAll('input');
      for (const [index, value] of [[0, 'Kimi'], [1, 'https://kimi.example/v1'], [2, 'kimi-key'], [3, 'moonshot-v1-8k']]) {
        Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(inputs[index], value);
        inputs[index].dispatchEvent(new Event('input', { bubbles: true })); await tick();
      }
      const fetchButton = [...custom.querySelectorAll('button')].find(button => button.textContent === 'Fetch Models');
      fetchButton.click(); await tick();
      check(fetchButton.disabled && fetchButton.textContent.includes('Fetching'), 'Loading is per provider');
      check(!inputs[3].disabled, 'Manual model input stays editable while fetching');
      check(window.calls.fetchModels.apiKey === 'kimi-key', 'Discovery uses draft credentials');
      window.resolveModels({ models: ['suggested-a', 'suggested-b'] }); await tick();
      check(inputs[3].list.options.length === 2, 'Suggestions connected to model input');
      check(form.querySelector('datalist').options.length === 0, 'Suggestions isolated by provider');
      check(inputs[3].value === 'moonshot-v1-8k', 'Unlisted manual model preserved');
      fetchButton.click(); await tick();
      window.resolveModels({ error: 'Failed to fetch models (HTTP 401).' }); await tick();
      check(custom.querySelector('[role=alert]').textContent.includes('Failed to fetch models'), 'Fetch error shown');
      check(inputs[3].value === 'moonshot-v1-8k' && !inputs[3].disabled, 'Failure preserves manual fallback');
      fetchButton.click(); await tick();
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(inputs[1], 'https://other.example/v1');
      inputs[1].dispatchEvent(new Event('input', { bubbles: true })); await tick();
      window.resolveModels({ models: ['stale-model'] }); await tick();
      check(inputs[3].list.options.length === 0, 'Stale endpoint response discarded');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(inputs[1], 'https://kimi.example/v1');
      inputs[1].dispatchEvent(new Event('input', { bubbles: true })); await tick();
      custom.requestSubmit(); await tick();
      check(window.calls.saves[1].name === 'Kimi', 'Custom name saved');
      check(window.calls.saves[1].baseUrl === 'https://kimi.example/v1', 'Custom endpoint saved');
      document.querySelector('#open').click(); await tick();
      check(button('Kimi'), 'Saved custom provider appears');
      button('Kimi').click(); await tick();
      check(window.fixtureState.target.model === 'moonshot-v1-8k', 'Custom model selected');
      [...custom.querySelectorAll('button')].find(button => button.textContent === 'Delete').click(); await tick();
      [...form.querySelectorAll('button')].find(button => button.textContent === 'Delete').click(); await tick();
      document.querySelector('#open').click(); await tick();
      check(!button('Kimi') && !button('OpenAI'), 'Deleted providers hidden');
      check(document.querySelector('dialog').textContent.includes('No cloud providers configured. Add one in Settings.'), 'Single empty state');
    })()`);
    console.log('Cloud/local selection, VRAM retention, unload, load sequence and key settings passed.');
  } finally { window.destroy(); await fs.rm(directory, { recursive: true, force: true }); }
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
