const { app, BrowserWindow } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const esbuild = require('esbuild');
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'projects-ui-'));
  const window = new BrowserWindow({ show: false, width: 1280, height: 900, webPreferences: { sandbox: true } });
  try {
    await esbuild.build({ entryPoints: [path.join(__dirname, 'fixtures/projects.jsx')], bundle: true, outfile: path.join(directory, 'fixture.js'), define: { 'process.env.NODE_ENV': '"test"' } });
    await fs.writeFile(path.join(directory, 'index.html'), '<style>:root{--surface:#181818;--surface-raised:#222;--text-primary:#eee;--text-muted:#aaa;--border:#444;--input:#292929;--accent:#dba487;--on-accent:#181818}body{margin:0;background:var(--surface);font-family:Arial}</style><link rel="stylesheet" href="fixture.css"><div id="root"></div><script src="fixture.js"></script>');
    await window.loadFile(path.join(directory, 'index.html'));
    await window.webContents.executeJavaScript(`(async () => {
      const wait = () => new Promise(resolve => setTimeout(resolve, 80));
      const check = (condition, message) => { if (!condition) throw new Error(message); };
      const button = text => [...document.querySelectorAll('button')].find(node => node.textContent.trim() === text);
      const type = (node, text) => { Object.getOwnPropertyDescriptor(node instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set.call(node, text); node.dispatchEvent(new Event('input', { bubbles: true })); };
      await wait();
      check(document.querySelectorAll('.project-card').length === 1, 'Project grid loaded');
      type(document.querySelector('[aria-label="Search projects"]'), 'nothing'); await wait();
      check(document.querySelectorAll('.project-card').length === 0, 'Search filters cards');
      type(document.querySelector('[aria-label="Search projects"]'), 'site'); await wait();
      document.querySelector('[aria-label="Expand Website chats"]').click(); await wait();
      check(document.querySelector('.project-nav-threads').textContent.includes('Project chat'), 'Nested project chat');
      check(!document.querySelector('[aria-label="Saved chats"]').textContent.includes('Project chat'), 'Project chat excluded from global history');
      document.querySelector('.project-card-link').click(); await wait();
      check(document.querySelector('.project-markdown strong').textContent === 'Launch', 'Markdown goal rendered');
      button('Edit Goal').click(); await wait();
      type(document.querySelector('textarea'), 'Updated **goal**'); await wait(); button('Save Goal').click(); await wait();
      check(document.querySelector('.project-markdown').textContent.includes('Updated goal'), 'Goal saved');
      type(document.querySelector('[aria-label="Custom Instructions"]'), 'Use tests'); await wait(); button('Save Instructions').click(); await wait();
      check((await window.api.getProject('p1')).custom_instructions === 'Use tests', 'Instructions persisted');
      button('Change Folder').click(); await wait(); check((await window.api.getProject('p1')).root_path === '/work/new-folder', 'Root changed');
      check(document.querySelector('.project-path').textContent === '/work/new-folder', 'Root displayed');
      const transfer = new DataTransfer(); transfer.items.add(new File(['Specification'], 'spec.md', { type: 'text/markdown' }));
      document.querySelector('.project-drop').dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: transfer })); await wait();
      check(document.querySelector('.project-file').textContent.includes('spec.md'), 'Context uploaded');
      document.querySelector('[aria-label="Remove spec.md"]').click(); await wait(); check(!document.querySelector('.project-file'), 'Context removed');
      type(document.querySelector('textarea[placeholder="What would you like to work on?"]'), 'Build the homepage'); await wait(); button('Start New Chat').click(); await wait();
      check(window.startedChat.id === 'p1' && window.startedChat.prompt === 'Build the homepage', 'Project chat dispatch');
      document.querySelector('.project-chat').click(); await wait(); check(window.loadedChat === 'c1', 'Recent chat navigation');
      button('All Projects').click(); await wait(); document.querySelector('[aria-label="Unpin Website"]').click(); await wait();
      check(!document.querySelector('[aria-label="Pinned Projects"]'), 'Pin group updates');
      button('Create New Project').click(); await wait(); check(document.querySelector('dialog').open, 'Creation modal');
      type(document.querySelector('dialog input'), 'New Idea'); await wait(); button('Choose Folder').click(); await wait(); button('Create Project').click(); await wait();
      check(window.createdProject.name === 'New Idea' && window.createdProject.root_path === '/work/new-folder', 'Create fields submitted');
      check(document.querySelector('h1').textContent === 'New Idea', 'New project opens in hub');
    })()`);
    await esbuild.build({ entryPoints: [path.join(__dirname, 'fixtures/projectNavigation.jsx')], bundle: true, outfile: path.join(directory, 'navigation.js'), define: { 'process.env.NODE_ENV': '\"test\"' } });
    await fs.writeFile(path.join(directory, 'navigation.html'), '<div id="root"></div><script src="navigation.js"></script>');
    await window.loadFile(path.join(directory, 'navigation.html'));
    await window.webContents.executeJavaScript(`(async () => {
      const wait = () => new Promise(resolve => setTimeout(resolve, 80));
      const check = (condition, message) => { if (!condition) throw new Error(message); };
      for (let i = 0; i < 40 && (!document.querySelector('#start') || document.querySelector('#start').disabled); i++) await wait();
      document.querySelector('#start').click();
      for (let i = 0; i < 40 && !window.generation; i++) await wait();
      check(window.linked.projectId === 'p1', 'Session is linked before generation');
      check(window.prepared.sessionId === window.linked.id && window.prepared.text === 'Project prompt', 'Prompt uses linked session');
      check(window.generation.sessionId === window.linked.id, 'Generation retains project session');
      check(!document.querySelector('#start'), 'Starting a project chat switches to chat view');
      const composer = document.querySelector('textarea');
      Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(composer, 'Unsent draft');
      composer.dispatchEvent(new Event('input', { bubbles: true })); await wait();
      [...document.querySelectorAll('button')].find(button => button.textContent.trim() === 'Projects').click(); await wait();
      check(document.querySelector('#start'), 'Project navigation opens workspace');
      [...document.querySelectorAll('button')].find(button => button.textContent.trim() === 'Back to Chat').click(); await wait();
      check(document.querySelector('textarea').value === 'Unsent draft', 'View navigation preserves chat draft');
    })()`);
    console.log('Projects UI: grid search, nested chats, Markdown editing, pinning, context files, folder binding, chat navigation, and modal creation passed.');
  } finally { window.destroy(); await fs.rm(directory, { recursive: true, force: true }); }
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
