const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Module = require('node:module');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'settings-hierarchy-'));
const original = Module._load;
Module._load = function(name, ...args) {
  if (name === 'electron') return { app: { isReady: () => true, getPath: () => dir } };
  return original.call(this, name, ...args);
};
const { db, initDatabase, closeDatabase } = require('../src/main/db');
const profiles = require('../src/main/profileSettings');
const sessions = require('../src/main/sessionManager');
const agents = require('../src/main/agentManager');
const { getEffectiveSettings } = require('../src/main/settingsResolver');
try {
  initDatabase();
  profiles.saveProfileSettings(null, { systemPrompt: 'Global instructions', temperature: 1, topP: 0.8, maxTokens: 200 });
  profiles.saveProfileSettings('/model-a', { systemPrompt: 'Model instructions', temperature: 0.3, topK: 20 });
  let state = profiles.getSessionSettings('draft', '/model-a');
  assert.equal(state.effective.temperature, 0.3);
  assert.equal(state.effective.topP, 0.8);
  assert.equal(state.effective.systemPrompt, 'Model instructions');
  assert.equal(state.source, 'model');
  assert.equal(state.exists, false);
  sessions.saveSessionSamplingParams('draft', '/model-a', { temperature: 0, top_p: 0 });
  agents.saveSessionPrompt('draft', '', '/model-a');
  state = profiles.getSessionSettings('draft', '/model-a');
  assert.equal(state.source, 'chat');
  assert.equal(state.effective.temperature, 0);
  assert.equal(state.effective.topP, 0);
  assert.equal(state.effective.systemPrompt, '');
  assert.equal(sessions.loadSession('draft').overrides.systemPrompt, '');
  assert.equal(sessions.getSessionSamplingParams('draft', '/model-a').params.top_k, 20);
  assert.equal(sessions.getSessionSamplingParams('draft', '/model-b').params.top_k, 40);
  agents.applyAgent('draft', null, '/model-a');
  state = profiles.getSessionSettings('draft', '/model-a');
  assert.deepEqual(state.overrides, {});
  assert.equal(state.effective.temperature, 0.3);
  const prompt = require('../src/main/promptBuilder').prepareChatMessages({ sessionId: 'draft', modelId: '/model-a', userText: 'Hello' });
  assert.ok(prompt.some(message => message.content.includes('Model instructions')));
  const message = sessions.saveMessage('draft', 'user', 'Branch point');
  sessions.saveSessionSamplingParams('draft', '/model-a', { top_k: 10 });
  const branch = sessions.branchChat('draft', message.id);
  assert.equal(profiles.getSessionSettings(branch.sessionId, '/model-a').effective.topK, 10);
  closeDatabase(); initDatabase();
  assert.equal(profiles.getSessionSettings('draft', '/model-a').effective.topK, 10);
  assert.equal(profiles.getProfileSettings().perModelConfigs['/model-a'].temperature, 0.3);
  profiles.saveProfileSettings('/model-a', null);
  assert.equal(profiles.getSessionSettings('draft', '/model-a').effective.temperature, 1);
  assert.throws(() => profiles.saveProfileSettings('/model-a', { temperature: 9 }), /Invalid sampling/);
  assert.throws(() => profiles.saveProfileSettings('/model-a', { systemPrompt: 123 }), /Invalid system/);
  const effective = getEffectiveSettings({ overrides: { temperature: 0, systemPrompt: '', maxTokens: -1 } }, 'a', { temperature: 1, systemPrompt: 'global', maxTokens: 99, perModelConfigs: { a: { temperature: 0.5 } } });
  assert.equal(effective.temperature, 0); assert.equal(effective.systemPrompt, ''); assert.equal(effective.maxTokens, -1);
  assert.equal(profiles.getSessionSettings('memory-chat', '/memory-model').effective.memoryEnabled, true);
  profiles.saveProfileSettings(null, { memoryEnabled: false, compactionEnabled: false });
  assert.equal(profiles.getSessionSettings('memory-chat', '/memory-model').effective.memoryEnabled, false);
  profiles.saveProfileSettings('/memory-model', { memoryEnabled: true });
  assert.equal(profiles.getSessionSettings('memory-chat', '/memory-model').effective.memoryEnabled, true);
  profiles.saveSessionMemorySettings('memory-chat', '/memory-model', { memoryEnabled: false, compactionEnabled: true });
  let memoryState = profiles.getSessionSettings('memory-chat', '/memory-model');
  assert.equal(memoryState.effective.memoryEnabled, false);
  assert.equal(memoryState.effective.compactionEnabled, true);
  const memoryManager = require('../src/main/memoryManager');
  memoryManager.addPermanentMemory({ category: 'fact', content: 'Secret remembered preference', alwaysInject: true });
  const isolated = require('../src/main/promptBuilder').prepareChatMessages({ sessionId: 'memory-chat', modelId: '/memory-model', userText: 'Hello', memoryEnabled: true });
  assert.ok(!isolated.some(message => /BACKGROUND KNOWLEDGE|Secret remembered preference/.test(message.content)));
  assert.match(isolated[0].content, /Memory Palace is disabled/);
  const tools = require('../src/main/promptBuilder').getToolContext([], false).tools;
  assert.deepEqual(tools.map(tool => tool.function.name), ['manage_mcp_servers', 'approve_mcp_mutation', 'get_recent_chat_history']);
  closeDatabase(); initDatabase();
  assert.equal(profiles.getSessionSettings('memory-chat', '/memory-model').effective.memoryEnabled, false);
  profiles.saveSessionMemorySettings('memory-chat', '/memory-model', { memoryEnabled: null });
  assert.equal(profiles.getSessionSettings('memory-chat', '/memory-model').effective.memoryEnabled, true);
  assert.throws(() => profiles.saveProfileSettings(null, { memoryEnabled: 'false' }), /Invalid/);
  assert.throws(() => profiles.saveSessionMemorySettings('memory-chat', '/memory-model', { compactionEnabled: 0 }), /Invalid/);
  assert.equal(getEffectiveSettings(null, 'missing', {}).thinkingBudget, -1);
  profiles.saveProfileSettings(null, { thinkingBudget: 1024 });
  profiles.saveProfileSettings('/thinking-model', { thinkingBudget: 4096 });
  assert.equal(profiles.getSessionSettings('thinking-chat', '/thinking-model').effective.thinkingBudget, 4096);
  sessions.saveSessionSamplingParams('thinking-chat', '/thinking-model', { thinking_budget: 2048 });
  assert.equal(profiles.getSessionSettings('thinking-chat', '/thinking-model').params.thinking_budget, 2048);
  closeDatabase(); initDatabase();
  assert.equal(profiles.getSessionSettings('thinking-chat', '/thinking-model').effective.thinkingBudget, 2048);
  sessions.saveSessionSamplingParams('thinking-chat', '/thinking-model', { thinking_budget: -1 });
  assert.equal(profiles.getSessionSettings('thinking-chat', '/thinking-model').effective.thinkingBudget, -1);
  sessions.saveSessionSamplingParams('thinking-chat', '/thinking-model', null);
  assert.equal(profiles.getSessionSettings('thinking-chat', '/thinking-model').effective.thinkingBudget, 4096);
  assert.equal(profiles.getSessionSettings(null, '/other-model').effective.thinkingBudget, 1024);
  for (const thinkingBudget of [-2, 65537, Infinity, '1024']) {
    assert.throws(() => profiles.saveProfileSettings('/thinking-model', { thinkingBudget }), /Invalid sampling/);
  }
  for (const thinkingBudget of [0, 255, 257, 2500, 65536]) {
    profiles.saveProfileSettings('/thinking-model', { thinkingBudget });
    assert.equal(profiles.getSessionSettings(null, '/thinking-model').effective.thinkingBudget, thinkingBudget);
  }
  console.log('Three-tier resolution, zero/empty overrides, model switching, prompt assembly, reset, persistence, branching and validation passed.');
} finally { closeDatabase(); Module._load = original; fs.rmSync(dir, { recursive: true, force: true }); }
